const nameGirl = 'Em';
const giftUrl = '';
const eventName = 'Chúc Mừng 20-10';
const titleCard = 'Tặng Em :>';
const contentCard = 'Chúc Em 20/10 tràn ngập niềm vui và những nụ cười. Mong điều đẹp nhất sẽ đến với Em trong hôm nay và cả những ngày sau. Wish you all the best <3';
const contentCard = 'Wish you all the best <3';
const giftImage = 'hot-girl.png';
const base64 = '';
const giftImageBase64 = "data:image/png;base64, " + base64;
